### ISSUE TITLE
Release vim-chrome as a vim plugin!

### ISSUE THREAD

**Issue by egonSchiele** [mklabs/vimfiles#1]
vim-chrome is very useful! Would you consider releasing it as a plugin?

**Comment by mklabs** [comment]
Hi @egonSchiele 

Someone took it and gave it a proper repo: https://github.com/muttonhead/vim-chrome

That being said, this plugin could be reworked and cover a lot more use cases.

**Comment by mklabs** [comment]
I won't have the time nor the energy to work on this for a long time. I committed a doc to reference the old plugin with 102c150a750a8079c21bf1b3c6f088d086a6defc

I may reopen this when and if I rework on this chrome plugin idea.
